server:
  port: '7002'

spring:
  application:
    name: PHOTOGRAPHY-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/vivaahmicroservice
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show_sql: 'true'
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
  zipkin:    base-url: http://127.0.0.1:9411/zipkin/
  
  
    


